# Generated by Django 5.1.3 on 2024-11-29 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowerShopFinanceTool", "0003_alter_prices_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 17, 27, 45, 455994, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
