# Generated by Django 5.1.3 on 2024-11-29 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowerShopFinanceTool", "0005_flower_image_alter_prices_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="image",
            field=models.ImageField(
                default="static/images/uploads/no_image.jpg",
                upload_to="static/images/uploads/",
            ),
        ),
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 29, 20, 3, 36, 880989, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
