# Generated by Django 5.1.3 on 2024-12-01 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowerShopFinanceTool", "0006_alter_flower_image_alter_prices_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="image",
            field=models.ImageField(
                default="uploads/no_image.jpg", upload_to="uploads"
            ),
        ),
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 1, 11, 31, 587124, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
