# Generated by Django 5.1.3 on 2024-12-01 21:30

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FlowerShopFinanceTool",
            "0008_alter_flower_id_alter_flower_image_alter_prices_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prices",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 1, 21, 30, 46, 60982, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="prices",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
